In [1]:
import numpy as np
import pandas as pd

In [2]:
animes = pd.read_csv('anime.csv')
rating= pd.read_csv('rating.csv')

In [3]:
animes.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [4]:
rating.head()

   user_id  anime_id  rating
0        1        20      -1
1        1        24      -1
2        1        79      -1
3        1       226      -1
4        1       241      -1

In [5]:

animes.dropna(inplace=True)
animes.drop_duplicates(subset='name')

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [6]:
animes.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [7]:
animes.iloc[0].genre

'Drama, Romance, School, Supernatural'

In [8]:

def convert(obj):
    return obj.split(', ')

In [9]:
animes['genre']=animes['genre'].apply(convert)

In [10]:
len(animes)

12017

In [11]:
animes['type']=animes['type'].apply(lambda x:x.split())
animes['episodes']=animes['episodes'].apply(lambda x:x.split())
animes['rating']=animes['rating'].apply(lambda x:np.array([x]))
animes.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"[Drama, Romance, School, Supernatural]",[Movie],[1],[9.37],200630
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy, Magic, Mil...",[TV],[64],[9.26],793665
2,28977,Gintama°,"[Action, Comedy, Historical, Parody, Samurai, ...",[TV],[51],[9.25],114262
3,9253,Steins;Gate,"[Sci-Fi, Thriller]",[TV],[24],[9.17],673572
4,9969,Gintama&#039;,"[Action, Comedy, Historical, Parody, Samurai, ...",[TV],[51],[9.16],151266

In [12]:
animes['tags']=animes['genre']+animes['type']+animes['episodes']

In [13]:
animes.head()

,anime_id,name,genre,type,episodes,rating,members,tags
0,32281,Kimi no Na wa.,"[Drama, Romance, School, Supernatural]",[Movie],[1],[9.37],200630,"[Drama, Romance, School, Supernatural, Movie, 1]"
1,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy, Magic, Mil...",[TV],[64],[9.26],793665,"[Action, Adventure, Drama, Fantasy, Magic, Mil..."
2,28977,Gintama°,"[Action, Comedy, Historical, Parody, Samurai, ...",[TV],[51],[9.25],114262,"[Action, Comedy, Historical, Parody, Samurai, ..."
3,9253,Steins;Gate,"[Sci-Fi, Thriller]",[TV],[24],[9.17],673572,"[Sci-Fi, Thriller, TV, 24]"
4,9969,Gintama&#039;,"[Action, Comedy, Historical, Parody, Samurai, ...",[TV],[51],[9.16],151266,"[Action, Comedy, Historical, Parody, Samurai, ..."

In [14]:
new_df=animes[['anime_id','name','rating','tags']]

In [15]:
new_df

,anime_id,name,rating,tags
0,32281,Kimi no Na wa.,[9.37],"[Drama, Romance, School, Supernatural, Movie, 1]"
1,5114,Fullmetal Alchemist: Brotherhood,[9.26],"[Action, Adventure, Drama, Fantasy, Magic, Mil..."
2,28977,Gintama°,[9.25],"[Action, Comedy, Historical, Parody, Samurai, ..."
3,9253,Steins;Gate,[9.17],"[Sci-Fi, Thriller, TV, 24]"
4,9969,Gintama&#039;,[9.16],"[Action, Comedy, Historical, Parody, Samurai, ..."
...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,[4.15],"[Hentai, OVA, 1]"
12290,5543,Under World,[4.28],"[Hentai, OVA, 1]"
12291,5621,Violence Gekiga David no Hoshi,[4.88],"[Hentai, OVA, 4]"
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,[4.98],"[Hentai, OVA, 1]"
12293,26081,Yasuji no Pornorama: Yacchimae!!,[5.46],"[Hentai, Movie, 1]"

In [16]:
def add(l):
    return  " ".join(str(x) for x in l)

In [17]:
new_df['tags'] = new_df['tags'].apply(add)

C:\Users\Cloud\AppData\Local\Temp/ipykernel_93352/811444876.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(add)

In [18]:
new_df.head()

,anime_id,name,rating,tags
0,32281,Kimi no Na wa.,[9.37],Drama Romance School Supernatural Movie 1
1,5114,Fullmetal Alchemist: Brotherhood,[9.26],Action Adventure Drama Fantasy Magic Military ...
2,28977,Gintama°,[9.25],Action Comedy Historical Parody Samurai Sci-Fi...
3,9253,Steins;Gate,[9.17],Sci-Fi Thriller TV 24
4,9969,Gintama&#039;,[9.16],Action Comedy Historical Parody Samurai Sci-Fi...

In [19]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\Cloud\AppData\Local\Temp/ipykernel_93352/3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [20]:
new_df.head()

,anime_id,name,rating,tags
0,32281,Kimi no Na wa.,[9.37],drama romance school supernatural movie 1
1,5114,Fullmetal Alchemist: Brotherhood,[9.26],action adventure drama fantasy magic military ...
2,28977,Gintama°,[9.25],action comedy historical parody samurai sci-fi...
3,9253,Steins;Gate,[9.17],sci-fi thriller tv 24
4,9969,Gintama&#039;,[9.16],action comedy historical parody samurai sci-fi...

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [22]:
cv.fit_transform(new_df['tags']).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [24]:
cv.get_feature_names()

['10',
 '100',
 '1006',
 '101',
 '102',
 '103',
 '104',
 '105',
 '108',
 '109',
 '11',
 '110',
 '112',
 '113',
 '114',
 '115',
 '117',
 '119',
 '12',
 '120',
 '124',
 '125',
 '127',
 '1274',
 '128',
 '13',
 '130',
 '1306',
 '132',
 '136',
 '137',
 '14',
 '140',
 '141',
 '142',
 '1428',
 '143',
 '145',
 '147',
 '1471',
 '148',
 '15',
 '150',
 '151',
 '153',
 '154',
 '155',
 '156',
 '1565',
 '16',
 '161',
 '162',
 '163',
 '164',
 '167',
 '17',
 '170',
 '172',
 '175',
 '178',
 '1787',
 '18',
 '180',
 '1818',
 '182',
 '19',
 '191',
 '192',
 '193',
 '195',
 '199',
 '20',
 '200',
 '201',
 '203',
 '21',
 '22',
 '220',
 '224',
 '225',
 '23',
 '237',
 '24',
 '240',
 '243',
 '25',
 '26',
 '260',
 '263',
 '27',
 '276',
 '28',
 '283',
 '29',
 '291',
 '296',
 '30',
 '300',
 '305',
 '31',
 '312',
 '32',
 '33',
 '330',
 '331',
 '34',
 '35',
 '358',
 '36',
 '365',
 '366',
 '37',
 '373',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '475',
 '48',
 '49',
 '50',
 '51',
 '510',
 '52',
 '526',
 '53',
 '54',
 '55',
 '56',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '694',
 '70',
 '71',
 '72',
 '726',
 '73',
 '74',
 '75',
 '76',
 '77',
 '773',
 '78',
 '79',
 '80',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 'action',
 'adventure',
 'ai',
 'arts',
 'cars',
 'comedy',
 'dementia',
 'demons',
 'drama',
 'ecchi',
 'fantasy',
 'fi',
 'game',
 'harem',
 'hentai',
 'historical',
 'horror',
 'josei',
 'kids',
 'life',
 'magic',
 'martial',
 'mecha',
 'military',
 'movie',
 'music',
 'mystery',
 'ona',
 'ova',
 'parody',
 'police',
 'power',
 'psychological',
 'romance',
 'samurai',
 'school',
 'sci',
 'seinen',
 'shoujo',
 'shounen',
 'slice',
 'space',
 'special',
 'sports',
 'super',
 'supernatural',
 'thriller',
 'tv',
 'unknown',
 'vampire',
 'yaoi',
 'yuri']

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
similarity = cosine_similarity(vector)

In [27]:
similarity

array([[1.        , 0.1490712 , 0.        , ..., 0.        , 0.        ,
        0.31622777],
       [0.1490712 , 1.        , 0.31622777, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.31622777, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.5       ],
       [0.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.5       ],
       [0.31622777, 0.        , 0.        , ..., 0.5       , 0.5       ,
        1.        ]])

In [28]:
new_df.rename(columns = {'name':'title'}, inplace = True)

C:\Users\Cloud\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [29]:
new_df

,anime_id,title,rating,tags
0,32281,Kimi no Na wa.,[9.37],drama romance school supernatural movie 1
1,5114,Fullmetal Alchemist: Brotherhood,[9.26],action adventure drama fantasy magic military ...
2,28977,Gintama°,[9.25],action comedy historical parody samurai sci-fi...
3,9253,Steins;Gate,[9.17],sci-fi thriller tv 24
4,9969,Gintama&#039;,[9.16],action comedy historical parody samurai sci-fi...
...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,[4.15],hentai ova 1
12290,5543,Under World,[4.28],hentai ova 1
12291,5621,Violence Gekiga David no Hoshi,[4.88],hentai ova 4
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,[4.98],hentai ova 1
12293,26081,Yasuji no Pornorama: Yacchimae!!,[5.46],hentai movie 1

In [30]:
def recommend(anime):
    index = new_df[new_df['title'] == anime].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].title)

In [31]:
recommend('Fullmetal Alchemist: Brotherhood')

Fullmetal Alchemist
Fullmetal Alchemist: The Sacred Star of Milos
Magi: The Kingdom of Magic
Magi: The Labyrinth of Magic
Magi: Sinbad no Bouken (TV)

In [32]:
import pickle

In [33]:
pickle.dump(new_df,open('anime_list1.pkl','wb'))
pickle.dump(similarity,open('similarity1.pkl','wb'))